### ISSUE TITLE
Asset host is not working

### ISSUE THREAD

**Issue by probus** [spanishdict/ghost-s3-compat#4]
Setting assetHost in the config doesn't seem to have any effect.

**Comment by JuanCaicedo** [comment]
I'm actually not sure how the `assetHost` works, it was part of the original code that we forked and I've never used that feature. Could you describe how you're trying to use it?

**Comment by probus** [comment]
I’m might not be using it as it was originally intended, but I use it to simply rewrite the url to my cdn (cloudfront) domain.

If I put `assetHost: 'https://mycdndomain.com/'` in the settings and upload an image from the editor, the resulting link I get should be `https://mycdndomain.com/.../image.jpg` instead of `https://mybucket.s3.amazonaws.com/.../image.jpg`.

**Comment by frankhinek** [comment]
@JuanCaicedo, the `assetHost` feature was removed in your [initial commit](https://github.com/spanishdict/ghost-s3-compat/commit/f858c9d20e79462d3cf3a9f646fcde290da6afb9), but is still listed in the README.  Since all references to `assetHost` were taken out you should probably update the README unless you plan to add the feature back.

For me this is a key feature which enables me to use a CDN as @probus is looking to do as well.

**Comment by frankhinek** [comment]
This is fixed in the [fork](https://github.com/frankhinek/ghost-storage-s3) I just published that handles all current AWS regions using the path-url style of accessing S3 buckets.

**Comment by JuanCaicedo** [comment]
Ah I see. My apologies @probus I hadn't realized this was still in the readme, and by doing that we were implying it was a supported feature! @frankhinek thanks for your work showing how to fix this. I'll push a PR and version soon

**Comment by JuanCaicedo** [comment]
This will be addressed in the above PR. 

@frankhinek I chose not to bring over most of your changes to the readme, particularly the installation docs. We specifically changed them by request from the Ghost founder in #5, so I feel confident about leaving them.

**Comment by JuanCaicedo** [comment]
Version 2.0.0 is published to npm now
